TpsReports.Website.CoreNet/Models/ErrorViewModel.cs
using System;

namespace TpsReports.Website.CoreNet.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TpsReports.Website.CoreNet/ViewModels/CreateReportViewModel.cs
namespace TpsReports.Website.CoreNet.ViewModels
{
    public class CreateReportViewModel
    {
        public string Name { get; set; }
        public string Host { get; set; }
        public int Version { get; set; }
    }
}

TpsReports.Website.CoreNet/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TpsReports.Website.CoreNet.Models;

namespace TpsReports.Website.CoreNet.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TpsReports.Website.CoreNet/Controllers/ReportsController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using TpsReports.Website.CoreNet.ViewModels;

namespace TpsReports.Website.CoreNet.Controllers
{
    public class ReportsController : Controller
    {
        public IActionResult Create()
        {
            var createReportViewModel = new CreateReportViewModel();

            createReportViewModel.Name = Guid.NewGuid().ToString();

            return View(createReportViewModel);
        }

        [HttpPost]
        public IActionResult Create(CreateReportViewModel createReportViewModel)
        {
            createReportViewModel.Host = Environment.MachineName;
            createReportViewModel.Version = 1;

            TempData["ReportName"] = createReportViewModel.Name;

            GenerateString();

            return RedirectToAction("Created");
        }

        public IActionResult Created()
        {
            @ViewBag.ReportName = TempData["ReportName"];

            return View();
        }

        private void GenerateString()
        {
            string foo = string.Empty;

            for (int iter = 0; iter < 10000; iter++)
            {
                var random = new Random(iter);

                foo = foo + char.ConvertFromUtf32(random.Next(0, 10_175));
            }
        }
    }
}

TpsReports.Website.CoreNet/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<br />

<p>Click <a asp-controller="Reports" asp-action="Create">Create Report</a> to create a report</p>

TpsReports.Website.CoreNet/Views/Reports/Create.cshtml
@model TpsReports.Website.CoreNet.ViewModels.CreateReportViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />

<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm("Create", "Reports", FormMethod.Post))
        {
            <form method="post" class="form">
                <div class="form-group">
                    <label>Report Name</label>
                    @Html.TextBoxFor(x => x.Name, new Dictionary<string, object> {{"class", "form-control"}})
                </div>
                <div class="form-group text-center">
                    <button type="submit" class="btn btn-default">SUBMIT</button>
                </div>
            </form>
        }
    </div>
</div>

TpsReports.Website.CoreNet/Views/Reports/Created.cshtml
@{
    ViewBag.Title = "Created";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />

<p>Successfully created report "@ViewBag.ReportName"</p>

TpsReports.Website.CoreNet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TpsReports.Website.CoreNet</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">TPS Report Core Net</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Reports" asp-action="Create">Create Report</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>v1.0.0</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>